"""
The Base class is used to define the common fields that multiple
models will use. It contains the core data attributes that are
shared by all operations involving that entity.

The Create class is derived from the Base class, but allows us to
specify the fields that are needed when creating an instance. It
includes fields necessary for creating a new record, while omitting
fields such as PKs that are auto-generated by the db.

The Response class (no suffix) contains all the data attributes,
including the PK. It is used when returning the response from the
API.

The orm_mode = True setting allows FastAPI to convert ORM objects
to Pydantic models seamlessly. In short, orm_mode = True is a
convenient way to make Pydantic models compatible with database
models used by ORMs, saving us from manually converting ORM objects
into dictionaries.
"""

from pydantic import BaseModel
from typing import Optional


class AccountBase(BaseModel):
    account_name: str
    website: Optional[str] = None
    type: Optional[str] = None
    description: Optional[str] = None
    primary_phone: Optional[str] = None
    secondary_phone: Optional[str] = None
    billing_street_1: Optional[str] = None
    billing_street_2: Optional[str] = None
    billing_city: Optional[str] = None
    billing_state: Optional[str] = None
    billing_zipcode: Optional[str] = None
    billing_country_id: Optional[int] = None
    shipping_street_1: Optional[str] = None
    shipping_street_2: Optional[str] = None
    shipping_city: Optional[str] = None
    shipping_state: Optional[str] = None
    shipping_zipcode: Optional[str] = None
    shipping_country_id: Optional[int] = None
    account_owner_id: Optional[int] = None


class AccountCreate(AccountBase):
    """
    The use of pass in the Create classes indicates that the
    Create model does not add any new fields beyond what is
    defined in the Base model. It simply inherits all fields
    from the base model.
    """

    pass


class Account(AccountBase):
    account_id: int

    class Config:
        from_attributes = True
